### ISSUE TITLE
Default OAuth Scopes have changed and tests fail

### ISSUE THREAD

**Issue by mirestrepo** [BrownUniversity/terraform-gcp-cluster#17]
Scopes that GKE adds are listed [here](https://cloud.google.com/kubernetes-engine/docs/how-to/access-scopes)

For some reason our change seems to indicate that we didn't use house a custom service account and now we do?

**Comment by digicosmos86** [comment]
So I guess because of the changes on our end (we are now using a custom service account?), we should change the expected values of the tests right?
